name: integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir: ['1.13', '1.12', '1.11', '1.10']
        otp: ['24.x', '23.x', '22.x']

    steps:
      - uses: actions/checkout@v3

      - name: Setup BEAM
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Restore dependencies cache
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}
            ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-
            ${{ runner.os }}-mix-${{ matrix.otp }}-
            ${{ runner.os }}-mix-

      - name: Install Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile

      - name: Generate JSON
        run: mix slack_api_docs.gen.json "/tmp/slack/web/docs"

      - name: Verify contents
        run: mix slack_api_docs.verify "/tmp/slack/web/docs"
